// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8sV1mN3Bwm-VxtlXBlroNbXow6CIk_DY',
    appId: '1:745750674380:web:03232169b03feebc77bb69',
    messagingSenderId: '745750674380',
    projectId: 'loginlogout03tkk24',
    authDomain: 'loginlogout03tkk24.firebaseapp.com',
    databaseURL: 'https://loginlogout03tkk24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginlogout03tkk24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMQiu8L-5AvoiaV0w9ty1S1Oaogyy3dGw',
    appId: '1:745750674380:android:1888e5764ae28e2977bb69',
    messagingSenderId: '745750674380',
    projectId: 'loginlogout03tkk24',
    databaseURL: 'https://loginlogout03tkk24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginlogout03tkk24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBLOO9NNbvCnVIM7NCLffTcYOqhB1Wjw',
    appId: '1:745750674380:ios:ed62195dca4b5d0c77bb69',
    messagingSenderId: '745750674380',
    projectId: 'loginlogout03tkk24',
    databaseURL: 'https://loginlogout03tkk24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginlogout03tkk24.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBLOO9NNbvCnVIM7NCLffTcYOqhB1Wjw',
    appId: '1:745750674380:ios:ed62195dca4b5d0c77bb69',
    messagingSenderId: '745750674380',
    projectId: 'loginlogout03tkk24',
    databaseURL: 'https://loginlogout03tkk24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginlogout03tkk24.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8sV1mN3Bwm-VxtlXBlroNbXow6CIk_DY',
    appId: '1:745750674380:web:59007125c8215a4a77bb69',
    messagingSenderId: '745750674380',
    projectId: 'loginlogout03tkk24',
    authDomain: 'loginlogout03tkk24.firebaseapp.com',
    databaseURL: 'https://loginlogout03tkk24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginlogout03tkk24.firebasestorage.app',
  );
}
